### PR TITLE
write comments to a static issue

### PR DESCRIPTION
**Pull request by LittleAprilFool**
finished

---
This change is [Reviewable](https://reviewable.io/reviews/leeleo3x/leossmartboy/1)

### CODE REVIEW

**Comment by aoli-al** [comment]
_[src/LeosSmartBoy/Commands/BillCommand.cs, line 216 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOKs_2Y8VudieQXUp-:-KVOKs_2Y8VudieQXUp0:b2nh8oq) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Commands/BillCommand.cs#L216)):_

> ``` Smalltalk
>                         KeyboardMarkupHelpers.CreateUserSelectionKeyboardMarkup(command, users, bill.SharedWith));
>                 case Bill.Status.Sealed:
>                     return await responseDelegate("Amount: " + bill.AmountString + "\nSelected Users: " + string.Join(", ", users.Where(u => bill.SharedWith.Contains(u.Id)).Select(u => u.LastName + ' ' + u.FirstName)) + "\nTestIssue: \n https://github.com/RoommateX/test/issues/16", null);
> ```

???

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1)_

**Comment by LittleAprilFool** [comment]
what's the problem

**Comment by aoli-al** [comment]
Review status: 0 of 8 files reviewed at latest revision, 15 unresolved discussions.

---

_[src/LeosSmartBoy/Program.cs, line 16 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVON7ZTMiW1ppPPcDPS:-KVON7ZTMiW1ppPPcDPT:b-f4f0nl) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Program.cs#L16)):_

> ``` Smalltalk
>             var configuration = builder.Build();
> 
>             BotService service = new BotService(configuration["ApiKey"], configuration["GithubID"], configuration["GithubSecret"]);
> ```

I prefer to create GithubBot here instead of in BotService.

---

_[src/LeosSmartBoy/Commands/BillCommand.cs, line 39 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOKUI-HKuFcxSTaqbi:-KVOKUI-HKuFcxSTaqbj:b2nh8oq) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Commands/BillCommand.cs#L39)):_

> ``` Smalltalk
>             var message = args.Message;
>             var chat = message.Chat;
> //if (chat.Type != ChatType.Group && chat.Type != ChatType.Supergroup) return;
> ```

???

---

_[src/LeosSmartBoy/Commands/BillCommand.cs, line 40 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOKZekCerFtKk1JPLO:-KVOKZekCerFtKk1JPLP:bhz1esd) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Commands/BillCommand.cs#L40)):_

> ``` Smalltalk
>             var chat = message.Chat;
> //if (chat.Type != ChatType.Group && chat.Type != ChatType.Supergroup) return;
>             Console.WriteLine(message);
> ```

Remove debug code.

---

_[src/LeosSmartBoy/Commands/RegisterCommand.cs, line 6 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOKx4dfbH2W_hEMvId:-KVOKx4dfbH2W_hEMvIe:byn1zmu) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Commands/RegisterCommand.cs#L6)):_

> ``` Smalltalk
> using Telegram.Bot.Args;
> using Telegram.Bot.Types;
> using System;
> ```

Remove unused library.

---

_[src/LeosSmartBoy/Models/Github.cs, line 9 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOL1YMz3Y41noCy5l6:-KVOL1YMz3Y41noCy5l7:bp3falr) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Models/Github.cs#L9)):_

> ``` Smalltalk
>         public string scopes;
>         public string note;
>         public string note_url;
> ```

Code style. Use nodeUrl.

---

_[src/LeosSmartBoy/Services/BotService.cs, line 102 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOLBzjAIysohLFQspD:-KVOLBzjAIysohLFQspE:bp1ma5q) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/BotService.cs#L102)):_

> ``` Smalltalk
>             // BotClient.SendTextMessageAsync(args.Message.Chat.Id, "hhh", false, false, 0, kb);
> ```

Remove unused code.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 36 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOLLmbfcQZkb4Mjnc8:-KVOLLmbfcQZkb4Mjnc9:bhwjhg4) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L36)):_

> ``` Smalltalk
>             //GetIssue();
>             //Test();
>             //CreateComment("hahahaha");
> ```

Same, remove unused code.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 48 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOLOziSS3fLJ6gVNn0:-KVOLOziSS3fLJ6gVNn1:b-72hya) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L48)):_

> ``` Smalltalk
>             var users = storageManager.GetChatUsers(bill.ChatId);
> 
>             string commentBody = "Amount: " + bill.AmountString + "\nSelected Users: " + string.Join(", ", users.Where(u => bill.SharedWith.Contains(u.Id)).Select(u => u.LastName + ' ' + u.FirstName)) + "\nCreated By: " + users.FirstOrDefault(u => u.Id==bill.CreatedBy).LastName + ' ' + users.FirstOrDefault(u => u.Id==bill.CreatedBy).FirstName;
> ```

Seperate code into multiple lines.

I'm still thinking about if we should pass storageManager to the GithubBot. I prefer to pass Bill only and Bill will hold the selected users and createdBy.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 49 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOMwQLv6OS_4_4I8mA:-KVOMwQLv6OS_4_4I8mB:bfb4jah) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L49)):_

> ``` Smalltalk
> 
>             string commentBody = "Amount: " + bill.AmountString + "\nSelected Users: " + string.Join(", ", users.Where(u => bill.SharedWith.Contains(u.Id)).Select(u => u.LastName + ' ' + u.FirstName)) + "\nCreated By: " + users.FirstOrDefault(u => u.Id==bill.CreatedBy).LastName + ' ' + users.FirstOrDefault(u => u.Id==bill.CreatedBy).FirstName;
>             string commentUrl = await CreateComment("16",commentBody);
> ```

Are we only using one comment?

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 53 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOLatfB4jz6E3dC4Xi:-KVOLatfB4jz6E3dC4Xj:b-6nzv6v) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L53)):_

> ``` Smalltalk
>         }
> 
>         public async Task Test()
> ```

Remove this.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 78 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOMUsvzgbEvOALGG2Z:-KVOMUsvzgbEvOALGG2_:brxlwwd) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L78)):_

> ``` Smalltalk
>             var stringIssue = await Task.Run(()=>JsonConvert.SerializeObject(issue));
>             var httpContent =  new StringContent(stringIssue, Encoding.UTF8, "application/json");
>             HttpResponseMessage response = await httpClient.PostAsync("/repos/RoommateX/test/issues", httpContent);
> ```

using var instead of HttpResponseMessage

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 79 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOMlu3T95x0aOZUss3:-KVOMlu3T95x0aOZUss4:b-3ni677) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L79)):_

> ``` Smalltalk
>             var httpContent =  new StringContent(stringIssue, Encoding.UTF8, "application/json");
>             HttpResponseMessage response = await httpClient.PostAsync("/repos/RoommateX/test/issues", httpContent);
>             var text = response.Content.ReadAsStringAsync().Result;
> ```

use var text = await response.Content.ReadAsStringAsync();
fix everywhere.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 90 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOMIHBsYmKEPqIjkQi:-KVOMIHBsYmKEPqIjkQj:bozwuya) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L90)):_

> ``` Smalltalk
>                 body = commentBody
>             };
>             var stringComment = await Task.Run(()=>JsonConvert.SerializeObject(comment));
> ```

Why using async here?

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 95 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOMPspBsnvoHOObVnM:-KVOMPsqjiOD8k9c6Ryt:b-of0aeh) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L95)):_

> ``` Smalltalk
>             var text = response.Content.ReadAsStringAsync().Result;
>             var definition = new {html_url = ""};
>             var textJson = await Task.Run(()=>JsonConvert.DeserializeAnonymousType(text, definition));
> ```

same question.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1)_

**Comment by aoli-al** [comment]
Review status: 0 of 8 files reviewed at latest revision, 15 unresolved discussions.

---

_[src/LeosSmartBoy/Services/GithubBotService.cs, line 48 at r1](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1#-KVOLOziSS3fLJ6gVNn0:-KVONUo04GI5vqhiohgg:b-a6xxrs) ([raw file](https://github.com/leeleo3x/leossmartboy/blob/d4674f0fbfc12080de8fb7de48003e2b580f1993/src/LeosSmartBoy/Services/GithubBotService.cs#L48)):_
<details><summary>

<i>Previously, Leeleo3x (Ao Li) wrote…</i></summary>



> Seperate code into multiple lines.
> 
> I'm still thinking about if we should pass storageManager to the GithubBot. I prefer to pass Bill only and Bill will hold the selected users and createdBy.
> </details>
> So here in Bill will hold the userList instants instead of the ids.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leeleo3x/leossmartboy/1)_

**Pull request closed without merging**
